# Generated by Django 5.0.2 on 2024-03-27 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_books'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projectmodule',
            table='projectmodule',
        ),
        migrations.AlterModelTable(
            name='usertask',
            table='usertask',
        ),
    ]
