# Generated by Django 5.0.2 on 2024-04-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_bug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertask',
            name='status',
        ),
        migrations.RemoveField(
            model_name='usertask',
            name='totalUtilMinutes',
        ),
        migrations.AddField(
            model_name='usertask',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usertask',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterModelTable(
            name='usertask',
            table='user_task',
        ),
    ]
